### ISSUE TITLE
Admins can merge suites 

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#179]
Use case: grouping many standalone singles into a suite, adding a standalone single to an existing suite as a bedroom.

**Comment by esoterik** [comment]
Process: go to suite show, select suite to merge from dropdown, get taken to form to confirm and optionally rename the suite (number will default to the suite from the show view)

**Comment by orenyk** [comment]
Ok, problem number 1 - how do we maintain the original suites? Currently we're using `belongs_to :suite` in the Room model, so when we replace those associations for the new suite we'll lose that information. We could use `remove_suite` and `restore_suite` to archive the last known suite for each room, which could be nice because then we can potentially suggest a split when we implement #180. I've gotta stop on this for now but I have a feature spec in place and can try to continue over the weekend.

**Comment by orenyk** [comment]
After discussions with @esoterik we're not going to deactivate the old suite, we're just going to destroy it. Also, make sure both suites belong to the same building (change the collection) and just destroy the old ones.
