### ISSUE TITLE
Admins can Bulk-add Facilities Information

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#20]
We need to figure out a good format for this. We might be using some internal API for usage at Yale, but we should implement something more general as well.

Blocked on #9.

**Comment by orenyk** [comment]
We just received the spreadsheets from the Dean's office with the housing info; it's not complete to the room level but we might still be able to use it. Let's use this issue to discuss the format and how best to import it. We can also write a one-off Ruby script / Rake task to handle this specific import rather than build it into the codebase.
