### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#28]
Users should be able to sign up for accounts.

**Comment by orenyk** [comment]
Open issues:

* What to do with the Devise registerable module
* Are we actually adding user registration?

**Comment by orenyk** [comment]
After completing #10 and #127, I'm not sure that this makes sense any more. Admins will create other admins one at a time (since IDR won't have access to non-YC data) and students will need to be granted access via bulk-registration and log in via CAS, so I'm not sure who we'd allow to sign up manually. I'm going to close this issue and the PR, sorry @AlanLiu96!
