### ISSUE TITLE
Student suite selection 

### ISSUE THREAD

**Issue by orenyk** [YaleSTC/vesta#502]
We need to re-enable student suite selection. Admins should be able to select which "mode" of suite selection they want for a particular draw, since the two different methods aren't really compatible.

Also, we need to add the following validations to student suite selection:
* [ ] Group must be locked
* [x] Group must be in draw that is in suite_selection status (#501)

**Comment by esoterik** [comment]
this should re-enable this feature

**Comment by adwoabuadu** [comment]
@esoterik When you say "this should re-enable this feature" do you mean that the only thing left with this issue is to add the locking validation to suite selection?

**Comment by esoterik** [comment]
We already built student suite selection, but we disabled it in [this commit](https://github.com/YaleSTC/vesta/commit/c11e2465a67ab8910e5da9fd7d55dd1d9c96ee5e). The two methods of suite selection (students logging in and picking vs. housing reps submitting selections at draw) are not really compatible. 

This issue should add a setting to `Draw` that allows admins to select the kind of suite selection they want, defaulting to housing rep / admin selection. That setting should be referenced in the policies for the suite selection routes in order to dynamically change the method of suite selection available to users.

**Comment by adwoabuadu** [comment]
In terms of re-enabling student suite selection, would that involve more or less adding/re-activating the code that was deleted in that commit and then adding validations to the suite_selection spec? I know we also talked about the draw_policy file as well, so I'm trying to figure where that fits in as well.

**Comment by adwoabuadu** [comment]
Okay, so I have a few questions:

1. Should this be referenced in DrawPolicy? I think that makes the most sense, from what I can glean from reading it.

2. If so, would this involve adding another method to draw policy, something like suite_selection_mode or something between user.admin and user rep?

3. Would the validation for the suite being locked be added to the suite_selection_spec file?
