### ISSUE TITLE
Intent Deadline

### ISSUE THREAD

**Issue by esoterik** [YaleSTC/vesta#51]
Draws should have a deadline for intent submission. After this deadline passes, students in the draw who have not submitted intent will default to living on campus (or, potentially make this configurable by admins)

**Comment by orenyk** [comment]
After reviewing some of our notes from the Residential College admins, it looks like at least one is opposed to any kind of intent assumption (Trumbull) and would just have the admin bother the students offline until they either indicated intent themselves or verbally told the admin who would then make the selection on behalf of the student.

We can still add this deadline and ultimately use it for sending reminder e-mails, but we can also expand this issue to include the admin report of students/intent as well as their ability to indicate intent. Does that make sense?

**Comment by orenyk** [comment]
Ok, thinking some more about this - would we prefer to keep the admin reports as separate routes from the student ones or just have a single route with different content depending on `current_user`? It gets even more confusing because it may also depend on the stage of the draw process we're in.

My first thought was just to use a nested route, `/draws/:id/students` and the columns / actions would change based on who was viewing and what was going on (e.g. pre-intent, we'd see the student name, their intent (maybe as an inline form with a dropdown to update the value as an admin), during the group phase we could see the students and their group (again, potentially as a dropdown), and maybe the same during the draw itself depending on how we handle oversubscription). At the same token, I figured we could use that same route for students to see everyone else's status, although now that I'm thinking about it, I'm not sure why that route would be meaningful for students since we'll likely give them something like `/draws/:id/groups` for group selection.

I'm also considering a general dashboard / status page for admins, but that would be a separate issue. Any thoughts on how you see this playing out would be great, thanks!

**Comment by orenyk** [comment]
Some notes from a phone conversation:

1. General dashboard with metrics and links through to specific reports relating to each aspect (e.g. intent, groups, etc) -->  we can also include buttons to send reminder e-mails manually.
2. No defaulting any kind of intent selection

Integration test:

1. visit draw page
2. test to see that intent metrics are correct
3. click through to intent report (`/draws/:id/intent`)
4. test for specific content
5. test that admins can set intent via inline forms

**Comment by orenyk** [comment]
Ok, basic status page integration spec set up with intent metrics, although the query used is super janky and needs to be extracted into a query object. I'll do that and work on the reports next.

**Comment by orenyk** [comment]
Added the query object, cleaned up rubocop. I'm starting to feel like this might be enough to merge in so I might extract just the status page as a separate issue, reassign #77 to that issue, and then continue here from there. @esoterik thoughts?

**Comment by orenyk** [comment]
I'm going to start fresh with a new branch that doesn't use JS for time, but the report will also be spun off as a separate issue from the deadline. This issue will now handle the following:

* [ ] Add Draw phase enum with `draft` and `pre-lottery`
* [ ] Add Draw attribute for intent deadline
* [ ] Add route / button on draw page to promote a draw from draft to pre-lottery, which will also queue e-mails to all the students to submit intent and form groups by deadline
